### ISSUE TITLE
Does this library work on linux?

### ISSUE THREAD

**Issue by dataplayer12** [manashmndl/SerialPort#17]
Hi, this is a great library. Thanks for making this open.

I would like to connect to a serial port on linux. In the header file, I noticed that `windows.h` is imported, which most likely means that the library does not support linux. Is that true? If yes, can you recommend a library for communicating with a serial port on linux?

**Comment by carllocos** [comment]
In one of the comments from the blog post related to the project , @manashmandal mentions that linux support is future work. The comment was made 3 years ago tho. And based on the commit log, I do not think this has been added.
This is unfortunate, because linux support is certainly desirable :)  

@dataplayer12 I'm no expert in the serial topic, but project [serial](https://github.com/wjwwood/serial) seems to support what you are looking for.

**Comment by dataplayer12** [comment]
Thanks for telling me about project serial. This is exactly what I am looking for. This SerialPort project seems to have been abandoned a long time ago.
